require:
  - rubocop-rspec

AllCops:
  RSpec:
    Patterns:
    - _test.rb
    - "(?:^|/)test/"

  RSpec/FactoryBot:
    Patterns:
    - spec/factories/**/*.rb

  Exclude:
    - db/**/*
  TargetRubyVersion: 2.4.5

Lint/HandleExceptions:
  Enabled: false

Lint/Void:
  # == operator used in void context in specs
  Enabled: false

Metrics/BlockNesting:
  # TODO: fix too much nesting
  Max: 4

Metrics/ClassLength:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Rails:
  Enabled: true

Style/BlockDelimiters:
  # allow multi-line blocks like expect { }
  Enabled: false

Style/CollectionMethods:
  # don't prefer map to collect, recuce to inject
  Enabled: false

Style/Documentation:
  # don't require classes to be documented
  Enabled: false

Style/Encoding:
  # no need to always specify encoding
  Enabled: false

# don't yell if a class/module/block/method does or doesn't have newlines
# surrounding it
Style/EmptyLinesAroundBlockBody:
  Enabled: false

Style/EmptyLinesAroundClassBody:
  Enabled: false

Style/EmptyLinesAroundModuleBody:
  Enabled: false

Style/EmptyLinesAroundMethodBody:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Style/Lambda:
  # TODO: replace all lambda with -> or Proc
  Enabled: false

Style/MultilineBlockChain:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    '%':  ()
    '%i': ()
    '%q': ()
    '%Q': ()
    '%r': '{}'
    '%s': ()
    '%w': '[]'
    '%W': ()
    '%x': ()

Style/PerlBackrefs:
  # TODO: regular expression matching with $1, $2, etc.
  Enabled: false

Style/RaiseArgs:
  # don't care for what kind of raise
  Enabled: false

Style/RedundantSelf:
  Enabled: false

Style/SignalException:
  # prefer raise to fail
  EnforcedStyle: only_raise

Style/StringLiterals:
  # use single or double-quoted strings, as you please
  Enabled: false

Style/TrailingBlankLines:
  Enabled: false

Style/WordArray:
  # %w vs. [ '', ... ]
  Enabled: false
