development: &development
  adapter: postgresql
  encoding: unicode
  pool: 10
  username: root
  database: rocket_dev
test:
  <<: *development
  database: rocket_test
integration: &default
  encoding: unicode
  pool: 20
